name: GitHub Actions
run-name: png2webp/link_shorten
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install 7-Zip
        run: choco install 7zip.install -y

      - name: Install FFmpeg
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest -Uri "https://ffmpeg.org/releases/ffmpeg-7.0.2.tar.xz" -OutFile "ffmpeg.tar.xz"
          7z x ffmpeg.tar.xz  # Extract the .tar.xz file
          7z x ffmpeg.tar  # Extract the .tar file to get FFmpeg
          Move-Item -Path "ffmpeg\*.*" -Destination "C:\ffmpeg"  # Move files to the target directory
          $env:PATH += ";C:\ffmpeg\bin"  # Update the PATH variable
          # Verify installation
          ffmpeg -version

      - name: Run png2webp/link_shorten PowerShell script
        run: pwsh -ExecutionPolicy Bypass -File "./png2webp.ps1"