name: GitHub Actions
run-name: png2webp/link_shorten
on: [push]
jobs:
  Post-Process-Notes:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install 7-Zip
        run: choco install 7zip.install -y

      - name: Install FFmpeg
        run: choco install ffmpeg -y

      - name: Run png2webp/link_shorten PowerShell script
        run: pwsh -ExecutionPolicy Bypass -File "./png2webp.ps1"